FROM maven:3.9.9 AS build

WORKDIR /app

COPY ./src ./
COPY ./pom.xml ./

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev", \
     "-Dspring.devtools.restart.enabled=true", \
     "-Dspring.devtools.livereload.enabled=true", \
     "-Dspring.devtools.remote.secret=mysecret"]