FROM maven:3.9.9-eclipse-temurin-23

WORKDIR /app

COPY ./src ./src
COPY ./pom.xml ./

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev", \
     "-Dspring.devtools.restart.enabled=true", \
     "-Dspring.devtools.livereload.enabled=true", \
     "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", \
     "-Dspring.devtools.remote.secret=mysecret"]
